site_name: Arista CVP collection
site_author: Arista Ansible Team
site_description: Arista Cloudvision collection's documentation
docs_dir: ansible_collections/arista/cvp/
site_favicon: docs/_media/favicon.ico
theme:
  name: material
  features:
    - instant
  font:
    text: Ubuntu
    code: Ubuntu Mono
extra_css:
  - docs/stylesheets/extra.css
copyright: Copyright &copy; 2019 - 2020 Arista Networks
repo_name: Github
repo_url: https://github.com/aristanetworks/ansible-cvp
use_directory_urls: true
nav:
  - Installation:
    - Requirements: docs/installation/requirements.md
    - Installation using ansible-galaxy: docs/installation/setup-galaxy.md
    - Installation using git: docs/installation/setup-git.md
    - Docker & Development: docs/installation/setup-docker.md
  - Getting Started: docs/getting-started.md
  - Roles documentation:
    - DHCP Configuration role: roles/dhcp_configuration/README.md
  - Modules documentation:
    - Module cv_facts: docs/modules/cv_facts.rst.md
    - Module cv_configlet: docs/modules/cv_configlet.rst.md
    - Module cv_container: docs/modules/cv_container.rst.md
    - Module cv_device: docs/modules/cv_device.rst.md
    - Module cv_tasks: docs/modules/cv_task.rst.md
  - About:
    - Contribution Guide: contributing.md
    - Ansible Galaxy page: https://galaxy.ansible.com/arista/cvp
    - Arista Validated Design: https://github.com/aristanetworks/ansible-avd
    - Arista Automation Examples: https://github.com/aristanetworks/netdevops-examples

markdown_extensions:
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      separator: "-"
      permalink: "#"
      baselevel: 1
