name: Mkdocs
on:
  push:
jobs:
  'doc':
    name: 'Update Public documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Setup Python 3 on runner'
        uses: actions/setup-python@v1.2.0
        with:
          python-version: '3.x'
      - name: 'Build mkdocs content'
        run: |
            pip install -r requirements.txt
            cd ansible_collections/arista/cvp/docs
            pip install -r requirements.txt
            make build_modules
            cd ../../../../
            mkdocs build -f mkdocs.yml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./site
